mutrack/mutrack/urls.py
import debug_toolbar
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin

from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/?$', auth_views.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/?$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    url(r'^tracker/', include('tracker.urls')),
    path('debug/', include(debug_toolbar.urls)),
]

mutrack/tracker/urls.py
from django.conf.urls import url

from . import views

app_name = 'tracker'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^artist/add/?$', views.ArtistCreate.as_view(), name='artist-create'),
    url(r'^artist/(?P<artist_name>[^/\s]+)/?$', views.ArtistView.as_view(),
        name='artist'),
    url(r'^artist/(?P<artist_name>[^/\s]+)/edit/?$',
        views.ArtistUpdate.as_view(), name='artist-update'),

    url(r'^album/(?P<artist_name>[^/\s]+)/(?P<album_name>[^/\s]+)/?$',
        views.AlbumView.as_view(), name='album'),
    url(r'^album/add/?$', views.AlbumCreate.as_view(), name='album-create'),
    url(r'^album/(?P<artist_name>[^/\s]+)/(?P<album_name>[^/\s]+)/edit/?$',
        views.AlbumUpdate.as_view(), name='album-update'),

    url(r'^add-listen/?$', views.ListenCreate.as_view(), name='listen-create'),
    url(r'^add-listen/(?P<artist_name>[^/\s]+)/(?P<album_name>[^/\s]+)/?$',
        views.ListenCreateForAlbum.as_view(), name='listen-create-for-album'),
]

mutrack/tracker/models.py
"""
models.py

File contains data models for music tracker application.
"""
import datetime
from urllib.parse import quote_plus

from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy

# For translation--lazy means it's only translated when it's needed
from django.utils.translation import ugettext_lazy as _

# Create your models here.

# No primary key required by default--see
# https://docs.djangoproject.com/en/1.11/topics/db/models/ ...
# ... #automatic-primary-key-fields

# Validators
def validate_zero_to_five(value):
    if value < 0.0 or value > 5.0:
        raise ValidationError(_('Value not between 0 and 5.'))

class PrimaryGenreManager(models.Manager):
    """Manager for PrimaryGenre model.
    """
    def get_by_natural_key(self, name):
        """Method to allow identification of a PrimaryGenre by name.

        Otherwise would use primary key, which isn't particularly meaningful.
        Helpful for serialization/fixtures.
        """
        return self.get(name=name)


class PrimaryGenre(models.Model):
    """A model representing a particular genre of music.

    These genres will be deliberately broad, so that there are only a handful.
    """
    objects = PrimaryGenreManager()

    name = models.CharField(max_length=60, unique=True)

    def __str__(self):
        return self.name


class ArtistManager(models.Manager):
    """Manager for Artist model.
    """
    def get_by_natural_key(self, name):
        """Method to allow identification of an Artist by name.

        Otherwise would use primary key, which isn't particularly meaningful.
        Helpful for serialization/fixtures.
        """
        return self.get(name=name)


class Artist(models.Model):
    """Model representing an artist.
    """
    objects = ArtistManager()

    name = models.CharField(max_length=120, unique=True)

    def __str__(self):
        return self.name

    def quoted_name(self):
        """Get 'quoted' name using pluses as spaces for use in URLs."""
        return quote_plus(self.name)

    def get_absolute_url(self):
        """Get url to detail page for the model instance.
        """
        return reverse_lazy('tracker:artist',
                            kwargs={'artist_name': self.quoted_name()})

    class Meta:
        ordering = ('name',)


class Album(models.Model):
    """Model representing an album.
    """
    name = models.CharField(max_length=120)
    year = models.IntegerField()
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    rating = models.FloatField(validators=[validate_zero_to_five])
    primary_genres = models.ManyToManyField(PrimaryGenre)
    secondary_genres = models.CharField(max_length=200, blank=True, default='')
    comments = models.TextField(blank=True, default='')
    listen_link = models.URLField(blank=True, default='')

    def __str__(self):
        return '{} [{}]'.format(self.name, self.artist.name)

    def get_absolute_url(self):
        """Get url to detail page for the model instance.
        """
        return reverse_lazy('tracker:album',
                            kwargs={'album_name': self.quoted_name(),
                                    'artist_name': self.artist.quoted_name()})

    def artist_name(self):
        return self.artist.name

    def quoted_name(self):
        """Get 'quoted' name using pluses as spaces for use in URLs."""
        return quote_plus(self.name)

    def all_listens(self):
        """Return all listens for this album."""
        return self.listen_set.filter(album=self)

    def last_five_listens(self):
        """Return five most recent listens for this album."""
        return self.all_listens()[:5]

    def last_five_listens_label(self):
        """Return text label for displaying "last five listens" in a view."""
        last_five = self.last_five_listens()
        if not last_five:
            return ''
        else:
            return 'Last {} listens:'.format(min((self.number_of_plays(), 5)))

    def last_listen(self):
        """Return most recent listen for this album."""
        all_listens = self.all_listens()
        if all_listens:
            return all_listens[0]
        else:
            return None

    def last_listen_date_ymd(self):
        """Return date of most recent listen as a string in YYYY/MM/DD format.

        If no last listen, will return 'No listens'
        """
        last_listen = self.last_listen()
        if last_listen:
            return last_listen.slash_date_ymd()
        else:
            return 'No listens'

    def last_listen_date_mdy(self):
        """Return date of most recent listen as a string in MM/DD/YY format.

        If no last listen, will return 'No listens'
        """
        last_listen = self.last_listen()
        if last_listen:
            return last_listen.slash_date_mdy()
        else:
            return 'No listens'

    def number_of_plays(self):
        """Return number of listens for this album."""
        return len(self.all_listens())

    class Meta:
        unique_together = ('name', 'artist')
        ordering = ('-rating', 'artist', 'name')


class Listen(models.Model):
    """A model representing an instance of listening to an album.
    """
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    listen_date = models.DateField(default=datetime.date.today, null=True)

    def __str__(self):
        return '{} ({})'.format(self.album, self.listen_date)

    def get_absolute_url(self):
        """Get url to detail page for the model instance.
        """
        return reverse_lazy(
            'tracker:album',
            kwargs={'album_name': self.album.quoted_name(),
                    'artist_name': self.album.artist.quoted_name()})

    def artist_name(self):
        return self.album.artist_name()

    def album_name(self):
        return self.album.name

    def slash_date_ymd(self):
        """Return listen date in YYYY/MM/DD format.

        If no date, 'Unknown date' is returned.
        """
        if self.listen_date is not None:
            return '{:04d}/{:02d}/{:02d}'.format(self.listen_date.year,
                                                 self.listen_date.month,
                                                 self.listen_date.day)
        else:
            return 'Unknown date'

    def slash_date_mdy(self):
        """Return listen date in MM/DD/YY format.

        If no date, 'Unknown date' is returned.
        """
        if self.listen_date is not None:
            return '{:d}/{:d}/{:02d}'.format(self.listen_date.month,
                                             self.listen_date.day,
                                             self.listen_date.year % 100)
        else:
            return 'Unknown date'

    def default_date(self):
        """Return listen date in default datetime.date format.

        If no date, 'Unknown date' is returned.
        """
        if self.listen_date is not None:
            return self.listen_date
        else:
            return 'Unknown date'

    class Meta:
        ordering = ('-listen_date',)

mutrack/tracker/forms.py
"""
forms.py

Module for holding custom forms for the tracker application.

"""

from django import forms

from .models import Listen

class ListenForm(forms.ModelForm):

    class Meta:
        model = Listen
        fields = ['album', 'listen_date']


class ListenFormForAlbum(ListenForm):

    def __init__(self, *args, **kwargs):
        super(ListenFormForAlbum, self).__init__(*args, **kwargs)

        self.fields['album'].widget = forms.widgets.HiddenInput()

mutrack/tracker/views.py
import copy
from urllib.parse import unquote_plus

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Album, Artist, Listen
from .forms import ListenForm, ListenFormForAlbum

class IndexView(LoginRequiredMixin, generic.ListView):
    """Index view for the tracker application.
    """
    template_name = 'tracker/index.html'
    context_object_name = 'album_list'

    def get_queryset(self):
        """Get the list of albums to display by default on the index page.

        """
        return Album.objects.all()


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Album-related views ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

class AlbumView(LoginRequiredMixin, generic.DetailView):
    """Detail view for an individual album.
    """
    model = Album

    def get_object(self):
        """Get the object we're looking for.

        Uses the album_name named group in the URL. Redefined so I don't have
        to use the (meaningless) primary key for the album in the URL.
        """
        artist_name = unquote_plus(self.kwargs['artist_name'])
        album_name = unquote_plus(self.kwargs['album_name'])
        super_qset = super(AlbumView, self).get_queryset()

        filterset = super_qset.filter(artist__name__iexact=artist_name,
                                      name__iexact=album_name)

        return filterset[0]

    def get_context_data(self, **kwargs):
        """Get context data for the view.
        """
        # Call super's method
        context = super(AlbumView, self).get_context_data(**kwargs)

        querystr = '{artist}+{album}'.format(
            album=self.kwargs['album_name'], artist=self.kwargs['artist_name'])

        youtube_search_link = (f'https://www.youtube.com/results?search_query='
                               f'{querystr}')
        context['youtube_search_link'] = youtube_search_link

        return context


class AlbumCreate(LoginRequiredMixin, generic.edit.CreateView):
    """View for creating a new Album.
    """
    model = Album
    fields = ['name', 'artist', 'year', 'rating', 'primary_genres',
              'secondary_genres', 'comments']
    template_name = 'tracker/generic_form.html'

    def get_context_data(self, **kwargs):
        """Get context data for this view.
        """
        # Call super
        context = super(AlbumCreate, self).get_context_data(**kwargs)
        context['action'] = 'Add'
        context['model_name'] = 'Album'
        return context


class AlbumUpdate(LoginRequiredMixin, generic.edit.UpdateView):
    """View for updating an Album.
    """
    model = Album
    fields = ['name', 'artist', 'year', 'rating', 'primary_genres',
              'secondary_genres', 'comments']
    template_name = 'tracker/generic_form.html'

    def get_object(self):
        """Get the object we're looking for.
        """
        artist_name = unquote_plus(self.kwargs['artist_name'])
        album_name = unquote_plus(self.kwargs['album_name'])
        super_qset = super(AlbumUpdate, self).get_queryset()

        filterset = super_qset.filter(artist__name__iexact=artist_name,
                                      name__iexact=album_name)
        return filterset[0]

    def get_context_data(self, **kwargs):
        """Get context data for this view.
        """
        # Call super
        context = super(AlbumUpdate, self).get_context_data(**kwargs)
        context['action'] = 'Edit'
        context['model_name'] = 'Album'
        return context


#~~~~~~~~~~~~~~~~~~~~~~~~~~~ Artist-related views ~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

class ArtistView(LoginRequiredMixin, generic.DetailView):
    """Detail view for an Artist.
    """
    model = Artist

    def get_object(self):
        """Get the object we're looking for, using the artist name.
        """
        artist_name = unquote_plus(self.kwargs['artist_name'])
        super_qset = super(ArtistView, self).get_queryset()
        filterset = super_qset.filter(name__iexact=artist_name)

        return filterset[0]

    def get_context_data(self, **kwargs):
        """Get context data for the view.
        """
        # Call super
        context = super(ArtistView, self).get_context_data(**kwargs)

        context['albums_by_artist'] = Album.objects.filter(
            artist__name__iexact=unquote_plus(self.kwargs['artist_name']))

        return context


class ArtistCreate(LoginRequiredMixin, generic.edit.CreateView):
    """View for creating a new Artist.
    """
    model = Artist
    fields = ['name']
    template_name = 'tracker/generic_form.html'

    def get_context_data(self, **kwargs):
        """Get context data for this view.
        """
        # Call super
        context = super(ArtistCreate, self).get_context_data(**kwargs)
        context['action'] = 'Add'
        context['model_name'] = 'Artist'
        return context


class ArtistUpdate(LoginRequiredMixin, generic.edit.UpdateView):
    """View for updating an Artist.
    """
    model = Artist
    fields = ['name']
    template_name = 'tracker/generic_form.html'

    def get_object(self):
        """Get the object we're looking for, using the artist name.
        """
        artist_name = unquote_plus(self.kwargs['artist_name'])
        super_qset = super(ArtistUpdate, self).get_queryset()
        filterset = super_qset.filter(name__iexact=artist_name)

        return filterset[0]

    def get_context_data(self, **kwargs):
        """Get context data for this view.
        """
        # Call super
        context = super(ArtistUpdate, self).get_context_data(**kwargs)
        context['action'] = 'Edit'
        context['model_name'] = 'Artist'
        return context


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Listen-related views ~~~~~~~~~~~~~~~~~~~~~~~~~~~#

class ListenCreate(LoginRequiredMixin, generic.edit.CreateView):
    """View for adding a new Listen.
    """
    model = Listen
    form_class = ListenForm
    template_name = 'tracker/generic_form.html'

    def get_context_data(self, **kwargs):
        """Get context data for this view.
        """
        # Call super
        context = super(ListenCreate, self).get_context_data(**kwargs)

        # Add the action and model name to the context for displaying
        context['action'] = 'Add'
        context['model_name'] = 'Listen'

        return context


class ListenCreateForAlbum(LoginRequiredMixin, generic.edit.CreateView):
    """View for creating a listen for a specific album.
    """
    model = Listen
    form_class = ListenFormForAlbum
    template_name = 'tracker/listen_for_album_form.html'

    def get_context_data(self, **kwargs):
        """Get context data for this view.
        """
        # Call super
        context = super(ListenCreateForAlbum, self).get_context_data(**kwargs)

        # Add the action and model name to the context for displaying
        context['action'] = 'Add'
        context['model_name'] = 'Listen'

        # Add the album name to the context (currently using Album.__str__)
        context['album'] = str(self.get_initial()['album'])

        return context

    def get_initial(self):
        initial = copy.copy(self.initial)
        initial['album'] = Album.objects.get(
            name__iexact=unquote_plus(self.kwargs['album_name']),
            artist__name__iexact=unquote_plus(self.kwargs['artist_name']))
        return initial

mutrack/tracker/templates/tracker/album_detail.html
{% extends "tracker/base.html" %}

{% block title %}{{ album.artist.name }} &ndash; {{ album.name }}{% endblock %}
{% block h1 %}<i>{{ album.name }}</i>{% endblock %}


{% block body-content %}

<div class="row">

  <div class="col-7">
    <ul>
      <li>Artist: {{ album.artist.name }}</li>
      <li>Year: {{ album.year }}</li>
      <li>Genres: {{ album.secondary_genres }}</li>
      <li>Rating: {{ album.rating }}</li>
      <li>Comments: {{ album.comments }}</li>
      <li><a href={{ youtube_search_link }} target=_blank rel="noopener noreferrer">
        Search on YouTube</a></li>

    </ul>
    <p><a href="{% url 'tracker:artist' album.artist.quoted_name %}">
      All albums by this artist</a></p>

    <p><a href="{% url 'tracker:album-update' album.artist.quoted_name album.quoted_name %}" class="btn btn-primary">
      Edit Album</a></p>

      <p><a href="{% url 'tracker:listen-create-for-album' album.artist.quoted_name album.quoted_name %}" class="btn btn-primary">
        Add Listen</a></p>
  </div>

  <div class="col-5">
    {{ album.last_five_listens_label }}
    <ul>
      {% for listen in album.last_five_listens %}
      <li>{{ listen.default_date }}</li>
      {% endfor %}
    </ul>
    <p>Total number of plays: {{ album.number_of_plays }}</p>

  </div>

</div class="row">


{% endblock %}

mutrack/tracker/templates/tracker/artist_detail.html
{% extends "tracker/base.html" %}

{% block title %}{{ artist.name }}{% endblock %}
{% block h1 %}{{ artist.name }}{% endblock %}


{% block body-content %}

<h2>Albums by this artist:</h2>
<ul>
  {% for album in albums_by_artist %}
  <li><a href="{% url 'tracker:album' artist.quoted_name album.quoted_name %}">
    <i>{{ album.name }}</i> ({{ album.year }})</a> ({{ album.rating }})</li>
  {% endfor %}
</ul>
<a href="{% url 'tracker:artist-update' artist.quoted_name %}" class="btn btn-primary">Edit Artist</a>

{% endblock %}

mutrack/tracker/templates/tracker/artist_form.html
{% extends "tracker/base-bootstrap.html" %}

{% block title %}{{ action }} Artist{% endblock %}
{% block h1 %}{{ action }} Artist{% endblock %}

{% block body-content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

mutrack/tracker/templates/tracker/base.html
{% extends "base.html" %}

{% block navblock %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="{% url 'tracker:index' %}">Album Tracker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="https://github.com/sierracodes/music-tracker/"
        target=_blank rel="noopener noreferrer">Github</a>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>
    <!-- Left justified links - note ml-auto class rather than mr-auto -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-item active nav-link" href="{% url 'tracker:album-create' %}">Add Album</a>
      </li>
      <li class="nav-item active">
        <a class="nav-item active nav-link" href="{% url 'tracker:artist-create' %}">Add Artist</a>
      </li>
      <li class="nav-item active">
        <a class="nav-item active nav-link" href="{% url 'tracker:listen-create' %}">Add Listen</a>
      </li>
      <!-- Log in or log out button -->
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-item active nav-link" href="{% url 'logout' %}">Log out</a>
        {# <a class="nav-item active nav-link" href="{% url 'logout' %}">Log out {{ user.username }}</a> #}
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-item active nav-link" href="{% url 'login' %}">Log in</a>
      </li>
      {% endif %}
    </ul>
    <!-- <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>

{% endblock %}

mutrack/tracker/templates/tracker/generic_form.html
{% extends "tracker/base.html" %}

{% block title %}{{ action }} {{ model_name }}{% endblock %}
{% block h1 %}{{ action }} {{ model_name }}{% endblock %}

{% block body-content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

mutrack/tracker/templates/tracker/index.html
{% extends "tracker/base.html" %}

{% load static %}
{% block headblock %}
<link rel="stylesheet" type="text/css" href="{% static 'tracker/style.css' %}" />
{% endblock %}

{% block title %}Album Tracker{% endblock %}
{# {% block h1 %}Album Tracker{% endblock %} #}


{% block body-content %}

<h2>All Albums</h2>

{# <form class="form-inline">#}
  {# <div class="form-group">#}
    {# <select id="search-selector">#}
      {# <option value="artist">Artist</option>#}
      {# <option value="album">Album</option>#}
      {# <option value="year">Year</option>#}
      {# <option value="genres">Genres</option>#}
    {# </select>#}
  {# </div>#}
  {# <div class="form-group mx-sm-3">#}
      {# <label for="album-search" class="sr-only">Search</label>#}
      {# <input type="search" class="form-control" id="album-search" placeholder="Search">#}
  {# </div>#}
{# </form>#}


<div class="table-responsive">
  <table class="table table-hover table-sm">
    <thead>
      <tr>
        <th>Artist</th>
        <th>Album</th>
        <th>Year</th>
        <th>Rating</th>
        <th>Genres</th>
        <th>Plays</th>
        <th>Last Listen</th>
      </tr>
    </thead>
    <tbody>
      <tr id="search-row">
        <td>
          <div class="form-group">
              <label for="album-search" class="sr-only">Artist</label>
              <input type="search" class="form-control" id="artist-search" placeholder="Artist">
          </div>
        </td>
        <td>
          <div class="form-group">
              <label for="album-search" class="sr-only">Album</label>
              <input type="search" class="form-control" id="album-search" placeholder="Album">
          </div>
        </td>
        <td class="search-data-cell">
          <div class="form-group">
              <label for="album-search" class="sr-only">Year</label>
              <input type="search" class="form-control" id="year-search" placeholder="Year">
          </div>
        </td>
        <td>
          <div class="form-group">
              <label for="album-search" class="sr-only">Rating</label>
              <input type="search" class="form-control" id="rating-search" placeholder="Rating">
          </div>
        </td>
        <td>
          <div class="form-group">
              <label for="album-search" class="sr-only">Genres</label>
              <input type="search" class="form-control" id="genre-search" placeholder="Genres">
          </div>
        </td>
        <td>
          <div class="form-group">
              <label for="album-search" class="sr-only">Plays</label>
              <input type="search" class="form-control" id="plays-search" placeholder="Plays">
          </div>
        </td>
        <td>
          <div class="form-group">
              <label for="album-search" class="sr-only">Last Listen</label>
              <input type="search" class="form-control" id="last-listen-search" placeholder="Last Listen">
          </div>
        </td>
      </tr>
      {% for album in album_list %}
      <tr class="album-data-row">
        <td><a class="block-anchor artist-cell" href="{% url 'tracker:artist' album.artist.quoted_name %}" >
          {{ album.artist.name }}</a></td>
        <td><a class="block-anchor album-cell" href="{% url 'tracker:album' album.artist.quoted_name album.quoted_name %}" title="{{ album.comments }}">
          {{ album.name }}</a></td>
        <td><a class="block-anchor year-cell" href="{% url 'tracker:album' album.artist.quoted_name album.quoted_name %}" title="{{ album.comments }}">
          {{ album.year }}</a></td>
        <td><a class="block-anchor rating-cell" href="{% url 'tracker:album' album.artist.quoted_name album.quoted_name %}" title="{{ album.comments }}">
          {{ album.rating }}</a></td>
        <td><a class="block-anchor genre-cell" href="{% url 'tracker:album' album.artist.quoted_name album.quoted_name %}" title="{{ album.comments }}">
          {{ album.secondary_genres }}</a></td>
        <td><a class="block-anchor plays-cell" href="{% url 'tracker:album' album.artist.quoted_name album.quoted_name %}" title="{{ album.comments }}">
          {{ album.number_of_plays }}</a></td>
        <td><a class="block-anchor last-listen-cell" href="{% url 'tracker:listen-create-for-album' album.artist.quoted_name album.quoted_name %}" title="Add Listen">
          {{ album.last_listen_date_mdy }}</a></td>
      </tr>
      {% endfor %}
    </tbody>

  </table>
</div>


{% endblock %}


{# Load some extra javasctipt #}
{% block end-of-body %}
<script type="text/javascript" src="{% static 'tracker/script.js' %}"></script>
{% endblock %}

mutrack/tracker/templates/tracker/listen_for_album_form.html
{% extends "tracker/base.html" %}

{% block title %}{{ action }} {{ model_name }}{% endblock %}
{% block h1 %}{{ action }} {{ model_name }}{% endblock %}

{% block body-content %}
<p>Album: {{ album }}</p>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}